market:
  service:
    catalogue:
      uri: lb://market-catalogue-service
      registration-id: keycloak
spring:
  boot:
    admin:
      client:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/market
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/market
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: DhsFC50IXFDItvZc25VlYM65bcaknW36
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          discovery:
            provider: keycloak
            client-id: manager-app
            client-secret: DhsFC50IXFDItvZc25VlYM65bcaknW36
            authorization-grant-type: client_credentials
            scope:
              - discovery
          metrics:
            provider: keycloak
            client-id: manager-app
            client-secret: DhsFC50IXFDItvZc25VlYM65bcaknW36
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/