server:
  port: 8888
spring:
  application:
    name: market-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nvgrig/market-cloud-config.git
          clone-on-start: true
          default-label: main
          search-paths:
            - '{application}/{profile}'