market:
  service:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8084
server:
  port: 8083
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8082/realms/market
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/market
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: UKUNilO8jhlzJGDbbEqkiDSqJAFHGmto
            scope:
              - openid
              - view_catalogue
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
