market:
  service:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8084
server:
  port: 8083
spring:
  application:
    name: market-customer-app
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/market
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/market
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: UKUNilO8jhlzJGDbbEqkiDSqJAFHGmto
            scope:
              - openid
              - view_catalogue
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
